# Generated by Django 6.0.1 on 2026-06-26 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('sale_type', models.CharField(choices=[('Tray', 'Tray'), ('Egg', 'Egg')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mix_name', models.CharField(max_length=120)),
                ('mixing_date', models.DateField(default=django.utils.timezone.localdate)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-mixing_date', 'mix_name'],
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('number_of_birds', models.PositiveIntegerField()),
                ('cost_per_bird', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_birds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Depleted', 'Depleted')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ['-purchase_date', 'breed'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_date', models.DateField(default=django.utils.timezone.localdate)),
                ('income_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-income_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='PoultryHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('bird_type', models.CharField(choices=[('Layer', 'Layer'), ('Broiler', 'Broiler'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ['house_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumption_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('feed_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='PoutryManagementSysyem.feedmix')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_consumptions', to='PoutryManagementSysyem.flock')),
            ],
            options={
                'ordering': ['-consumption_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedMixDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('feed_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='PoutryManagementSysyem.feedmix')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_mix_details', to='PoutryManagementSysyem.inventoryitem')),
            ],
            options={
                'ordering': ['inventory_item__item_name'],
            },
        ),
        migrations.AddField(
            model_name='flock',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flocks', to='PoutryManagementSysyem.poultryhouse'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='PoutryManagementSysyem.inventoryitem')),
            ],
            options={
                'ordering': ['-purchase_date', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('eggs_collected', models.PositiveIntegerField(default=0)),
                ('broken_eggs', models.PositiveIntegerField(default=0)),
                ('dirty_eggs', models.PositiveIntegerField(default=0)),
                ('good_eggs', models.PositiveIntegerField(default=0, editable=False)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_productions', to='PoutryManagementSysyem.flock')),
            ],
            options={
                'ordering': ['-production_date'],
                'unique_together': {('flock', 'production_date')},
            },
        ),
    ]
