# Generated by Django 6.0.6 on 2026-06-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsale',
            name='egg_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_sales', to='PoutryManagementSysyem.eggproduction'),
        ),
    ]
