# Generated by Django 6.0.6 on 2026-06-28 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0002_eggsale_egg_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_type', models.CharField(choices=[('Tray', 'Tray'), ('Egg', 'Egg')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_date', 'sale_type'],
            },
        ),
        migrations.AddField(
            model_name='eggsale',
            name='egg_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_sales', to='PoutryManagementSysyem.eggprice'),
        ),
    ]
