# Generated by Django 6.0.6 on 2026-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0003_eggprice_eggsale_egg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='breed',
            field=models.CharField(choices=[('ISA Brown', 'ISA Brown'), ('Lohmann Brown', 'Lohmann Brown'), ('Rhode Island Red', 'Rhode Island Red'), ('Kuroiler', 'Kuroiler'), ('Cobb 500', 'Cobb 500'), ('Ross 308', 'Ross 308'), ('Sasso', 'Sasso'), ('Local', 'Local'), ('Other', 'Other')], max_length=100),
        ),
    ]
