# Generated by Django 6.0.6 on 2026-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0005_rename_flock_status_to_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
