# Generated by Django 6.0.6 on 2026-06-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0007_feedmixdetail_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmix',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_mixes', to='PoutryManagementSysyem.purchase'),
        ),
    ]
