# Generated by Django 6.0.6 on 2026-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0008_feedmix_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmix',
            name='mix_name',
            field=models.CharField(choices=[('Layer Formula', 'Layer Formula'), ('Grower Formula', 'Grower Formula'), ('Protein Mix', 'Protein Mix'), ('Chick Starter', 'Chick Starter'), ('Broiler Starter', 'Broiler Starter'), ('Broiler Grower', 'Broiler Grower'), ('Broiler Finisher', 'Broiler Finisher'), ('Layer Mash', 'Layer Mash'), ('Grower Mash', 'Grower Mash'), ('Developer Mash', 'Developer Mash'), ('Breeder Mash', 'Breeder Mash'), ('Energy Mix', 'Energy Mix'), ('Empty Formula', 'Empty Formula'), ('Unlinked Formula', 'Unlinked Formula'), ('Custom Mix', 'Custom Mix')], max_length=120),
        ),
    ]
