# Generated by Django 6.0.6 on 2026-06-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0010_alter_purchase_category_alter_purchase_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmix',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feedmix',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='feedmix',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
