# Generated by Django 6.0.6 on 2026-06-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0011_feedmix_quantity_feedmix_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmix',
            name='item_name',
            field=models.CharField(choices=[('Layer Mash', 'Layer Mash'), ('Grower Mash', 'Grower Mash'), ('Starter Feed', 'Starter Feed'), ('Broiler Starter', 'Broiler Starter'), ('Broiler Grower', 'Broiler Grower'), ('Broiler Finisher', 'Broiler Finisher'), ('Chick Starter', 'Chick Starter'), ('Maize Bran', 'Maize Bran'), ('Soya', 'Soya'), ('Cotton Cake', 'Cotton Cake'), ('Concentrate', 'Concentrate'), ('Fish Meal', 'Fish Meal'), ('Bone Meal', 'Bone Meal'), ('Sunflower Cake', 'Sunflower Cake'), ('Shell', 'Shell'), ('Limestone', 'Limestone'), ('DCP', 'DCP'), ('Salt', 'Salt'), ('Vitamin Premix', 'Vitamin Premix'), ('Newcastle Vaccine', 'Newcastle Vaccine'), ('Medicine', 'Medicine'), ('Disinfectant', 'Disinfectant'), ('Receipt Book', 'Receipt Book'), ('Paper', 'Paper'), ('Pen', 'Pen'), ('File', 'File'), ('Fuel', 'Fuel'), ('Feeder', 'Feeder'), ('Drinker', 'Drinker'), ('Egg Tray', 'Egg Tray'), ('Crate', 'Crate'), ('Other', 'Other')], default='Maize Bran', max_length=120),
        ),
    ]
