# Generated by Django 6.0.6 on 2026-06-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0012_feedmix_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmix',
            name='item_name',
            field=models.CharField(choices=[('Layer Mash', 'Layer Mash'), ('Grower Mash', 'Grower Mash'), ('Starter Feed', 'Starter Feed'), ('Broiler Starter', 'Broiler Starter'), ('Broiler Grower', 'Broiler Grower'), ('Broiler Finisher', 'Broiler Finisher'), ('Chick Starter', 'Chick Starter'), ('Chick Mash', 'Chick Mash'), ('Layer Pellets', 'Layer Pellets'), ('Grower Pellets', 'Grower Pellets'), ('Broiler Pellets', 'Broiler Pellets'), ('Maize Bran', 'Maize Bran'), ('Whole Maize', 'Whole Maize'), ('Maize Germ', 'Maize Germ'), ('Wheat Bran', 'Wheat Bran'), ('Wheat Pollard', 'Wheat Pollard'), ('Rice Bran', 'Rice Bran'), ('Broken Rice', 'Broken Rice'), ('Sorghum', 'Sorghum'), ('Millet', 'Millet'), ('Cassava Flour', 'Cassava Flour'), ('Soya', 'Soya'), ('Soybean Meal', 'Soybean Meal'), ('Cotton Cake', 'Cotton Cake'), ('Groundnut Cake', 'Groundnut Cake'), ('Sunflower Cake', 'Sunflower Cake'), ('Sesame Cake', 'Sesame Cake'), ('Palm Kernel Cake', 'Palm Kernel Cake'), ('Concentrate', 'Concentrate'), ('Fish Meal', 'Fish Meal'), ('Blood Meal', 'Blood Meal'), ('Bone Meal', 'Bone Meal'), ('Meat And Bone Meal', 'Meat And Bone Meal'), ('Shell', 'Shell'), ('Oyster Shell', 'Oyster Shell'), ('Limestone', 'Limestone'), ('DCP', 'DCP'), ('Salt', 'Salt'), ('Vitamin Premix', 'Vitamin Premix'), ('Mineral Premix', 'Mineral Premix'), ('Amino Acid Premix', 'Amino Acid Premix'), ('Lysine', 'Lysine'), ('Methionine', 'Methionine'), ('Toxin Binder', 'Toxin Binder'), ('Molasses', 'Molasses'), ('Newcastle Vaccine', 'Newcastle Vaccine'), ('Medicine', 'Medicine'), ('Disinfectant', 'Disinfectant'), ('Receipt Book', 'Receipt Book'), ('Paper', 'Paper'), ('Pen', 'Pen'), ('File', 'File'), ('Fuel', 'Fuel'), ('Feeder', 'Feeder'), ('Drinker', 'Drinker'), ('Egg Tray', 'Egg Tray'), ('Crate', 'Crate'), ('Other', 'Other')], default='Maize Bran', max_length=120),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(choices=[('Layer Mash', 'Layer Mash'), ('Grower Mash', 'Grower Mash'), ('Starter Feed', 'Starter Feed'), ('Broiler Starter', 'Broiler Starter'), ('Broiler Grower', 'Broiler Grower'), ('Broiler Finisher', 'Broiler Finisher'), ('Chick Starter', 'Chick Starter'), ('Chick Mash', 'Chick Mash'), ('Layer Pellets', 'Layer Pellets'), ('Grower Pellets', 'Grower Pellets'), ('Broiler Pellets', 'Broiler Pellets'), ('Maize Bran', 'Maize Bran'), ('Whole Maize', 'Whole Maize'), ('Maize Germ', 'Maize Germ'), ('Wheat Bran', 'Wheat Bran'), ('Wheat Pollard', 'Wheat Pollard'), ('Rice Bran', 'Rice Bran'), ('Broken Rice', 'Broken Rice'), ('Sorghum', 'Sorghum'), ('Millet', 'Millet'), ('Cassava Flour', 'Cassava Flour'), ('Soya', 'Soya'), ('Soybean Meal', 'Soybean Meal'), ('Cotton Cake', 'Cotton Cake'), ('Groundnut Cake', 'Groundnut Cake'), ('Sunflower Cake', 'Sunflower Cake'), ('Sesame Cake', 'Sesame Cake'), ('Palm Kernel Cake', 'Palm Kernel Cake'), ('Concentrate', 'Concentrate'), ('Fish Meal', 'Fish Meal'), ('Blood Meal', 'Blood Meal'), ('Bone Meal', 'Bone Meal'), ('Meat And Bone Meal', 'Meat And Bone Meal'), ('Shell', 'Shell'), ('Oyster Shell', 'Oyster Shell'), ('Limestone', 'Limestone'), ('DCP', 'DCP'), ('Salt', 'Salt'), ('Vitamin Premix', 'Vitamin Premix'), ('Mineral Premix', 'Mineral Premix'), ('Amino Acid Premix', 'Amino Acid Premix'), ('Lysine', 'Lysine'), ('Methionine', 'Methionine'), ('Toxin Binder', 'Toxin Binder'), ('Molasses', 'Molasses'), ('Newcastle Vaccine', 'Newcastle Vaccine'), ('Medicine', 'Medicine'), ('Disinfectant', 'Disinfectant'), ('Receipt Book', 'Receipt Book'), ('Paper', 'Paper'), ('Pen', 'Pen'), ('File', 'File'), ('Fuel', 'Fuel'), ('Feeder', 'Feeder'), ('Drinker', 'Drinker'), ('Egg Tray', 'Egg Tray'), ('Crate', 'Crate'), ('Other', 'Other')], max_length=120),
        ),
    ]
