# Generated by Django 6.0.1 on 2026-06-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0013_alter_feedmix_item_name_alter_purchase_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poultryhouse',
            name='status',
            field=models.CharField(choices=[('Full capacity', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], default='Full capacity', max_length=20),
        ),
    ]
