# Generated by Codex on 2026-06-29

from django.db import migrations, models


def update_house_statuses(apps, schema_editor):
    PoultryHouse = apps.get_model('PoutryManagementSysyem', 'PoultryHouse')
    PoultryHouse.objects.filter(status='Active').update(status='Full capacity')
    PoultryHouse.objects.filter(status='Maintenance').update(status='Half capacity')
    PoultryHouse.objects.filter(status='Inactive').update(status='Empty')


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0014_alter_poultryhouse_status'),
    ]

    operations = [
        migrations.RunPython(update_house_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='poultryhouse',
            name='status',
            field=models.CharField(
                choices=[
                    ('Full capacity', 'Full capacity'),
                    ('Half capacity', 'Half capacity'),
                    ('Empty', 'Empty'),
                ],
                default='Full capacity',
                max_length=20,
            ),
        ),
    ]
