# Generated by Codex on 2026-06-29

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def populate_feed_mix_stock(apps, schema_editor):
    FeedMix = apps.get_model('PoutryManagementSysyem', 'FeedMix')
    FeedConsumption = apps.get_model('PoutryManagementSysyem', 'FeedConsumption')
    for feed_mix in FeedMix.objects.all():
        consumed = (
            FeedConsumption.objects.filter(feed_mix_id=feed_mix.pk).aggregate(total=Sum('quantity'))['total']
            or Decimal('0')
        )
        feed_mix.stock = (feed_mix.quantity or Decimal('0')) - consumed
        feed_mix.save(update_fields=['stock'])


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0015_alter_poultryhouse_status_capacity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmix',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(populate_feed_mix_stock, migrations.RunPython.noop),
    ]
