# Generated by Codex on 2026-06-29

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def populate_purchase_stock_balance(apps, schema_editor):
    Purchase = apps.get_model('PoutryManagementSysyem', 'Purchase')
    FeedMixDetail = apps.get_model('PoutryManagementSysyem', 'FeedMixDetail')
    for purchase in Purchase.objects.all():
        used_quantity = (
            FeedMixDetail.objects.filter(purchase_id=purchase.pk).aggregate(total=Sum('quantity'))['total']
            or Decimal('0')
        )
        purchase.stock_balance = (purchase.quantity or Decimal('0')) - used_quantity
        purchase.save(update_fields=['stock_balance'])


class Migration(migrations.Migration):

    dependencies = [
        ('PoutryManagementSysyem', '0016_feedmix_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stock_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(populate_purchase_stock_balance, migrations.RunPython.noop),
    ]
